app/urls.py
from django.urls import path
from app.views import *
app_name='app'
urlpatterns=[
    path('harrish/',harrish,name='harrish')
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'
urlpatterns=[
    path('prasanna/',prasanna,name='prasanna')
]

project6/urls.py
from django.contrib import admin
from django.urls import path,include
import app,app2 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
    path('app2/',include('app2.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.
def harrish(request):
    return render(request,'harrish.html')

app2/views.py
from django.shortcuts import render
# Create your views here.
def prasanna(request):
    return render(request,'prasanna.html')

templates/harrish.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title >Eg</title>
    <link rel="icon" href="desktop/pic.jpg">
    
</head>
<body>
    <center>
     
        <img src="{% static 'img/pic.jpg' %}" height=400px ""><br><br>
        <a href="{% url 'app2:prasanna'%}">click here</a><br><br>
        
    </center>
</body>
</html>

templates/prasanna.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hi....</h1>
        <a href="{% url 'app:harrish'%}">Return</a>
    </center>
</body>
</html>